import type { Metadata } from "next";
import "./globals.css";
import { Cinzel,Playfair_Display } from 'next/font/google'

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: "--font-cinzel",
})
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});
export const metadata: Metadata = {
  title: "ARTHOR PEMBROKE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${cinzel.variable} ${playfair.variable} h-full antialiased`}
    >
      <body  className={` min-h-full flex flex-col w-screen overflow-x-hidden`}>{children}</body>
    </html>
  );
}
